// Emits dist/theme.css: a Tailwind 4 @theme block with static values only, so the same
// file works in the web app (Tailwind) and the phone app (Uniwind). Fonts are not here;
// each app names its own font files.
import { mkdirSync, writeFileSync } from 'node:fs'

import { colors, radius } from './src/tokens.ts'

const lines: string[] = [
  '/* Generated by @prismark/theme from src/tokens.ts. Do not edit. */',
  '@theme {',
]
for (const [name, value] of Object.entries(colors)) lines.push(`  --color-${name}: ${value};`)
for (const [name, value] of Object.entries(radius)) {
  lines.push(name === 'DEFAULT' ? `  --radius: ${value}px;` : `  --radius-${name}: ${value}px;`)
}
lines.push('}', '')

mkdirSync('dist', { recursive: true })
writeFileSync('dist/theme.css', lines.join('\n'))
console.log('wrote dist/theme.css')
